### ISSUE TITLE
Mutating error object causes problems

### ISSUE THREAD

**Issue by kellyselden** [sindresorhus/p-retry#14]
Getting

```
(node:15140) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'attemptNumber' on string '
warning.js:18
┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\kelly\.config │
└────────────────────────────────────────────────────────────┘
'
```

We should instead send a new object to `onFailedAttempt`.

**Comment by sindresorhus** [comment]
You should not throw strings. I guess we could add a better error message for it when it encounters a non-error, but I don't like the idea of just handling thrown strings.

**Comment by ddgenome** [comment]
Unfortunately, sometimes packages you do not control throw non `Error`s.

**Comment by sindresorhus** [comment]
@ddgenome Open an issue on those packages. They should not throw non-Error's.

**Comment by lukiano** [comment]
Node itself throws Non-Errors, like some network errors. I just stumbled upon this, and added a try-catch inside my code to wrap them into an Error object so that this package can understand them.

**Comment by daveyarwood** [comment]
At my company, we use the [make-error](https://www.npmjs.com/package/make-error) package to create errors. This is a popular package with ~27 million weekly downloads. Would these errors also trip up p-retry and result in the "Non-error was thrown" message? I'm asking because we just ran into this error:

> Non-error was thrown: \"[object Object]\". You should only throw errors.

It isn't clear from the error message what we tried to throw, which is cumbersome. My best guess is that it could be a `make-error` object that we created.

I'm sure that there is a good reason for p-retry enforcing that only Error objects can be thrown, but it isn't clear to me -- it seems like an arbitrary decision that may be causing more harm than good. @sindresorhus Can you explain why p-retry does this?

**Comment by daveyarwood** [comment]
Possibly related to #25. It seems like the answer is probably that p-retry expects to be able to extend your error, which makes sense. Surely there is some way that p-retry could handle this internally, though, instead of disallowing a variety of things that are commonly thrown in JavaScript?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-retry/releases/tag/v7.0.0-0
